// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndwhfhihnqbutrrzrznl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kd2hmaGlobnFidXRycnpyem5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDI3NzgsImV4cCI6MjA3MzY3ODc3OH0.NObFzs-FSd0hnRCLQV5wL_4eAFyZQ5XNiLARcE86mZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});